
# [env]
# TERM = "xterm-256color"
#
[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "buttonless"
opacity = 0.98

# [window.dimensions]
# columns = 120
# lines = 40
#
# [window.padding]
# x = 5
# y = 5
