import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[ env ]
TERM = "xterm-256color"

[font]
size = 13
normal.family = "JetBrainsMono Nerd Font"

[window]
decorations = "buttonless"
opacity = 0.99

# [window.dimensions]
# columns = 120
# lines = 40
#
# [window.padding]
# x = 5
# y = 5
